// Code generated by proto watcher. DO NOT EDIT.
package commands

//MapXXX mapping ID to object
type MapXXX struct {
}

// NewObjectByID return new object from id
func (r *MapXXX) NewObjectByID(id uint16) (interface{}) {
	switch id {
	case 1: return new(Err)
	}
	return nil
}
