// Code generated by protoc-gen-go. DO NOT EDIT.
// source: latlng.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  Latlan keep latitue and longitude
//
type Latlng struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *Latlng) Reset()         { *m = Latlng{} }
func (m *Latlng) String() string { return proto.CompactTextString(m) }
func (*Latlng) ProtoMessage()    {}
func (*Latlng) Descriptor() ([]byte, []int) {
	return fileDescriptor_574bb5cd6b4e7063, []int{0}
}

func (m *Latlng) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Latlng.Unmarshal(m, b)
}
func (m *Latlng) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Latlng.Marshal(b, m, deterministic)
}
func (m *Latlng) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Latlng.Merge(m, src)
}
func (m *Latlng) XXX_Size() int {
	return xxx_messageInfo_Latlng.Size(m)
}
func (m *Latlng) XXX_DiscardUnknown() {
	xxx_messageInfo_Latlng.DiscardUnknown(m)
}

var xxx_messageInfo_Latlng proto.InternalMessageInfo

func (m *Latlng) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Latlng) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func init() {
	proto.RegisterType((*Latlng)(nil), "Latlng")
}

func init() { proto.RegisterFile("latlng.proto", fileDescriptor_574bb5cd6b4e7063) }

var fileDescriptor_574bb5cd6b4e7063 = []byte{
	// 75 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x49, 0x2c, 0xc9,
	0xc9, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe1, 0x62, 0xf3, 0x01, 0xf3, 0x85,
	0x04, 0xb8, 0x98, 0x73, 0x12, 0x4b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x18, 0x83, 0x40, 0x4c, 0xb0,
	0x48, 0x5e, 0xba, 0x04, 0x13, 0x54, 0x24, 0x2f, 0x3d, 0x89, 0x0d, 0xac, 0xc9, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x35, 0x73, 0x15, 0xaa, 0x44, 0x00, 0x00, 0x00,
}


func (m *Latlng) XXX_MapID() uint16 {
	return 3
}

func (m *Latlng) XXX_MapName() string {
	return "Latlng"
}
