// Code generated by protoc-gen-go. DO NOT EDIT.
// source: big_data_action.proto

package mock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  BigDataAction
//
type BigDataAction struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *BigDataAction) Reset()         { *m = BigDataAction{} }
func (m *BigDataAction) String() string { return proto.CompactTextString(m) }
func (*BigDataAction) ProtoMessage()    {}
func (*BigDataAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_008093fd18c82571, []int{0}
}

func (m *BigDataAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigDataAction.Unmarshal(m, b)
}
func (m *BigDataAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigDataAction.Marshal(b, m, deterministic)
}
func (m *BigDataAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigDataAction.Merge(m, src)
}
func (m *BigDataAction) XXX_Size() int {
	return xxx_messageInfo_BigDataAction.Size(m)
}
func (m *BigDataAction) XXX_DiscardUnknown() {
	xxx_messageInfo_BigDataAction.DiscardUnknown(m)
}

var xxx_messageInfo_BigDataAction proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BigDataAction)(nil), "BigDataAction")
}

func init() { proto.RegisterFile("big_data_action.proto", fileDescriptor_008093fd18c82571) }

var fileDescriptor_008093fd18c82571 = []byte{
	// 66 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xca, 0x4c, 0x8f,
	0x4f, 0x49, 0x2c, 0x49, 0x8c, 0x4f, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x57, 0xe2, 0xe7, 0xe2, 0x75, 0xca, 0x4c, 0x77, 0x49, 0x2c, 0x49, 0x74, 0x04, 0x0b, 0x27,
	0xb1, 0x81, 0xc5, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xd6, 0xa6, 0x61, 0x30, 0x00,
	0x00, 0x00,
}


func (m *BigDataAction) XXX_MapID() uint16 {
	return 1005
}

func (m *BigDataAction) XXX_MapName() string {
	return "BigDataAction"
}
