// Code generated by protoc-gen-go. DO NOT EDIT.
// source: slow_action.proto

package mock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  SlowAction
//
type SlowAction struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *SlowAction) Reset()         { *m = SlowAction{} }
func (m *SlowAction) String() string { return proto.CompactTextString(m) }
func (*SlowAction) ProtoMessage()    {}
func (*SlowAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cb445ec7584ce, []int{0}
}

func (m *SlowAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlowAction.Unmarshal(m, b)
}
func (m *SlowAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlowAction.Marshal(b, m, deterministic)
}
func (m *SlowAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlowAction.Merge(m, src)
}
func (m *SlowAction) XXX_Size() int {
	return xxx_messageInfo_SlowAction.Size(m)
}
func (m *SlowAction) XXX_DiscardUnknown() {
	xxx_messageInfo_SlowAction.DiscardUnknown(m)
}

var xxx_messageInfo_SlowAction proto.InternalMessageInfo

func (m *SlowAction) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*SlowAction)(nil), "SlowAction")
}

func init() { proto.RegisterFile("slow_action.proto", fileDescriptor_8e4cb445ec7584ce) }

var fileDescriptor_8e4cb445ec7584ce = []byte{
	// 76 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xce, 0xc9, 0x2f,
	0x8f, 0x4f, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe0,
	0xe2, 0x0a, 0xce, 0xc9, 0x2f, 0x77, 0x04, 0x8b, 0x09, 0x09, 0x71, 0xb1, 0x94, 0xa4, 0x56, 0x94,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0x85, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xaf, 0xd8, 0x7f, 0xfa, 0x3d, 0x00, 0x00, 0x00,
}


func (m *SlowAction) XXX_MapID() uint16 {
	return 1004
}

func (m *SlowAction) XXX_MapName() string {
	return "SlowAction"
}
