// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type.proto

package ptype

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	sourcecontextpb "google.golang.org/protobuf/types/known/sourcecontextpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The syntax in which a protocol buffer element is defined.
type Syntax int32

const (
	// Syntax `proto2`.
	Syntax_SYNTAX_PROTO2 Syntax = 0
	// Syntax `proto3`.
	Syntax_SYNTAX_PROTO3 Syntax = 1
)

var Syntax_name = map[int32]string{
	0: "SYNTAX_PROTO2",
	1: "SYNTAX_PROTO3",
}

var Syntax_value = map[string]int32{
	"SYNTAX_PROTO2": 0,
	"SYNTAX_PROTO3": 1,
}

func (x Syntax) String() string {
	return proto.EnumName(Syntax_name, int32(x))
}

func (Syntax) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{0}
}

// Basic field types.
type Field_Kind int32

const (
	// Field type unknown.
	Field_TYPE_UNKNOWN Field_Kind = 0
	// Field type double.
	Field_TYPE_DOUBLE Field_Kind = 1
	// Field type float.
	Field_TYPE_FLOAT Field_Kind = 2
	// Field type int64.
	Field_TYPE_INT64 Field_Kind = 3
	// Field type uint64.
	Field_TYPE_UINT64 Field_Kind = 4
	// Field type int32.
	Field_TYPE_INT32 Field_Kind = 5
	// Field type fixed64.
	Field_TYPE_FIXED64 Field_Kind = 6
	// Field type fixed32.
	Field_TYPE_FIXED32 Field_Kind = 7
	// Field type bool.
	Field_TYPE_BOOL Field_Kind = 8
	// Field type string.
	Field_TYPE_STRING Field_Kind = 9
	// Field type group. Proto2 syntax only, and deprecated.
	Field_TYPE_GROUP Field_Kind = 10
	// Field type message.
	Field_TYPE_MESSAGE Field_Kind = 11
	// Field type bytes.
	Field_TYPE_BYTES Field_Kind = 12
	// Field type uint32.
	Field_TYPE_UINT32 Field_Kind = 13
	// Field type enum.
	Field_TYPE_ENUM Field_Kind = 14
	// Field type sfixed32.
	Field_TYPE_SFIXED32 Field_Kind = 15
	// Field type sfixed64.
	Field_TYPE_SFIXED64 Field_Kind = 16
	// Field type sint32.
	Field_TYPE_SINT32 Field_Kind = 17
	// Field type sint64.
	Field_TYPE_SINT64 Field_Kind = 18
)

var Field_Kind_name = map[int32]string{
	0:  "TYPE_UNKNOWN",
	1:  "TYPE_DOUBLE",
	2:  "TYPE_FLOAT",
	3:  "TYPE_INT64",
	4:  "TYPE_UINT64",
	5:  "TYPE_INT32",
	6:  "TYPE_FIXED64",
	7:  "TYPE_FIXED32",
	8:  "TYPE_BOOL",
	9:  "TYPE_STRING",
	10: "TYPE_GROUP",
	11: "TYPE_MESSAGE",
	12: "TYPE_BYTES",
	13: "TYPE_UINT32",
	14: "TYPE_ENUM",
	15: "TYPE_SFIXED32",
	16: "TYPE_SFIXED64",
	17: "TYPE_SINT32",
	18: "TYPE_SINT64",
}

var Field_Kind_value = map[string]int32{
	"TYPE_UNKNOWN":  0,
	"TYPE_DOUBLE":   1,
	"TYPE_FLOAT":    2,
	"TYPE_INT64":    3,
	"TYPE_UINT64":   4,
	"TYPE_INT32":    5,
	"TYPE_FIXED64":  6,
	"TYPE_FIXED32":  7,
	"TYPE_BOOL":     8,
	"TYPE_STRING":   9,
	"TYPE_GROUP":    10,
	"TYPE_MESSAGE":  11,
	"TYPE_BYTES":    12,
	"TYPE_UINT32":   13,
	"TYPE_ENUM":     14,
	"TYPE_SFIXED32": 15,
	"TYPE_SFIXED64": 16,
	"TYPE_SINT32":   17,
	"TYPE_SINT64":   18,
}

func (x Field_Kind) String() string {
	return proto.EnumName(Field_Kind_name, int32(x))
}

func (Field_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{1, 0}
}

// Whether a field is optional, required, or repeated.
type Field_Cardinality int32

const (
	// For fields with unknown cardinality.
	Field_CARDINALITY_UNKNOWN Field_Cardinality = 0
	// For optional fields.
	Field_CARDINALITY_OPTIONAL Field_Cardinality = 1
	// For required fields. Proto2 syntax only.
	Field_CARDINALITY_REQUIRED Field_Cardinality = 2
	// For repeated fields.
	Field_CARDINALITY_REPEATED Field_Cardinality = 3
)

var Field_Cardinality_name = map[int32]string{
	0: "CARDINALITY_UNKNOWN",
	1: "CARDINALITY_OPTIONAL",
	2: "CARDINALITY_REQUIRED",
	3: "CARDINALITY_REPEATED",
}

var Field_Cardinality_value = map[string]int32{
	"CARDINALITY_UNKNOWN":  0,
	"CARDINALITY_OPTIONAL": 1,
	"CARDINALITY_REQUIRED": 2,
	"CARDINALITY_REPEATED": 3,
}

func (x Field_Cardinality) String() string {
	return proto.EnumName(Field_Cardinality_name, int32(x))
}

func (Field_Cardinality) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{1, 1}
}

// A protocol buffer message type.
type Type struct {
	// The fully qualified message name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The list of fields.
	Fields []*Field `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	// The list of types appearing in `oneof` definitions in this type.
	Oneofs []string `protobuf:"bytes,3,rep,name=oneofs,proto3" json:"oneofs,omitempty"`
	// The protocol buffer options.
	Options []*Option `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	// The source context.
	SourceContext *sourcecontextpb.SourceContext `protobuf:"bytes,5,opt,name=source_context,json=sourceContext,proto3" json:"source_context,omitempty"`
	// The source syntax.
	Syntax               Syntax   `protobuf:"varint,6,opt,name=syntax,proto3,enum=google.protobuf.Syntax" json:"syntax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{0}
}

func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (m *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(m, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

func (m *Type) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Type) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Type) GetOneofs() []string {
	if m != nil {
		return m.Oneofs
	}
	return nil
}

func (m *Type) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Type) GetSourceContext() *sourcecontextpb.SourceContext {
	if m != nil {
		return m.SourceContext
	}
	return nil
}

func (m *Type) GetSyntax() Syntax {
	if m != nil {
		return m.Syntax
	}
	return Syntax_SYNTAX_PROTO2
}

// A single field of a message type.
type Field struct {
	// The field type.
	Kind Field_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=google.protobuf.Field_Kind" json:"kind,omitempty"`
	// The field cardinality.
	Cardinality Field_Cardinality `protobuf:"varint,2,opt,name=cardinality,proto3,enum=google.protobuf.Field_Cardinality" json:"cardinality,omitempty"`
	// The field number.
	Number int32 `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	// The field name.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// The field type URL, without the scheme, for message or enumeration
	// types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
	TypeUrl string `protobuf:"bytes,6,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	// The index of the field type in `Type.oneofs`, for message or enumeration
	// types. The first type has index 1; zero means the type is not in the list.
	OneofIndex int32 `protobuf:"varint,7,opt,name=oneof_index,json=oneofIndex,proto3" json:"oneof_index,omitempty"`
	// Whether to use alternative packed wire representation.
	Packed bool `protobuf:"varint,8,opt,name=packed,proto3" json:"packed,omitempty"`
	// The protocol buffer options.
	Options []*Option `protobuf:"bytes,9,rep,name=options,proto3" json:"options,omitempty"`
	// The field JSON name.
	JsonName string `protobuf:"bytes,10,opt,name=json_name,json=jsonName,proto3" json:"json_name,omitempty"`
	// The string value of the default value of this field. Proto2 syntax only.
	DefaultValue         string   `protobuf:"bytes,11,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{1}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetKind() Field_Kind {
	if m != nil {
		return m.Kind
	}
	return Field_TYPE_UNKNOWN
}

func (m *Field) GetCardinality() Field_Cardinality {
	if m != nil {
		return m.Cardinality
	}
	return Field_CARDINALITY_UNKNOWN
}

func (m *Field) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetTypeUrl() string {
	if m != nil {
		return m.TypeUrl
	}
	return ""
}

func (m *Field) GetOneofIndex() int32 {
	if m != nil {
		return m.OneofIndex
	}
	return 0
}

func (m *Field) GetPacked() bool {
	if m != nil {
		return m.Packed
	}
	return false
}

func (m *Field) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Field) GetJsonName() string {
	if m != nil {
		return m.JsonName
	}
	return ""
}

func (m *Field) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

// Enum type definition.
type Enum struct {
	// Enum type name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Enum value definitions.
	Enumvalue []*EnumValue `protobuf:"bytes,2,rep,name=enumvalue,proto3" json:"enumvalue,omitempty"`
	// Protocol buffer options.
	Options []*Option `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	// The source context.
	SourceContext *sourcecontextpb.SourceContext `protobuf:"bytes,4,opt,name=source_context,json=sourceContext,proto3" json:"source_context,omitempty"`
	// The source syntax.
	Syntax               Syntax   `protobuf:"varint,5,opt,name=syntax,proto3,enum=google.protobuf.Syntax" json:"syntax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Enum) Reset()         { *m = Enum{} }
func (m *Enum) String() string { return proto.CompactTextString(m) }
func (*Enum) ProtoMessage()    {}
func (*Enum) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{2}
}

func (m *Enum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Enum.Unmarshal(m, b)
}
func (m *Enum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Enum.Marshal(b, m, deterministic)
}
func (m *Enum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Enum.Merge(m, src)
}
func (m *Enum) XXX_Size() int {
	return xxx_messageInfo_Enum.Size(m)
}
func (m *Enum) XXX_DiscardUnknown() {
	xxx_messageInfo_Enum.DiscardUnknown(m)
}

var xxx_messageInfo_Enum proto.InternalMessageInfo

func (m *Enum) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Enum) GetEnumvalue() []*EnumValue {
	if m != nil {
		return m.Enumvalue
	}
	return nil
}

func (m *Enum) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Enum) GetSourceContext() *sourcecontextpb.SourceContext {
	if m != nil {
		return m.SourceContext
	}
	return nil
}

func (m *Enum) GetSyntax() Syntax {
	if m != nil {
		return m.Syntax
	}
	return Syntax_SYNTAX_PROTO2
}

// Enum value definition.
type EnumValue struct {
	// Enum value name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Enum value number.
	Number int32 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	// Protocol buffer options.
	Options              []*Option `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EnumValue) Reset()         { *m = EnumValue{} }
func (m *EnumValue) String() string { return proto.CompactTextString(m) }
func (*EnumValue) ProtoMessage()    {}
func (*EnumValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{3}
}

func (m *EnumValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumValue.Unmarshal(m, b)
}
func (m *EnumValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumValue.Marshal(b, m, deterministic)
}
func (m *EnumValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumValue.Merge(m, src)
}
func (m *EnumValue) XXX_Size() int {
	return xxx_messageInfo_EnumValue.Size(m)
}
func (m *EnumValue) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumValue.DiscardUnknown(m)
}

var xxx_messageInfo_EnumValue proto.InternalMessageInfo

func (m *EnumValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnumValue) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *EnumValue) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

// A protocol buffer option, which can be attached to a message, field,
// enumeration, etc.
type Option struct {
	// The option's name. For protobuf built-in options (options defined in
	// descriptor.proto), this is the short name. For example, `"map_entry"`.
	// For custom options, it should be the fully-qualified name. For example,
	// `"google.api.http"`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The option's value packed in an Any message. If the value is a primitive,
	// the corresponding wrapper type defined in google/protobuf/wrappers.proto
	// should be used. If the value is an enum, it should be stored as an int32
	// value using the google.protobuf.Int32Value type.
	Value                *anypb.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{4}
}

func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (m *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(m, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Option) GetValue() *anypb.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("google.protobuf.Syntax", Syntax_name, Syntax_value)
	proto.RegisterEnum("google.protobuf.Field_Kind", Field_Kind_name, Field_Kind_value)
	proto.RegisterEnum("google.protobuf.Field_Cardinality", Field_Cardinality_name, Field_Cardinality_value)
	proto.RegisterType((*Type)(nil), "google.protobuf.Type")
	proto.RegisterType((*Field)(nil), "google.protobuf.Field")
	proto.RegisterType((*Enum)(nil), "google.protobuf.Enum")
	proto.RegisterType((*EnumValue)(nil), "google.protobuf.EnumValue")
	proto.RegisterType((*Option)(nil), "google.protobuf.Option")
}

func init() { proto.RegisterFile("type.proto", fileDescriptor_8eaed4801c3a9059) }

var fileDescriptor_8eaed4801c3a9059 = []byte{
	// 805 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x8e, 0xda, 0x56,
	0x14, 0x8e, 0x8d, 0xf1, 0xe0, 0xc3, 0xc0, 0xdc, 0xdc, 0x44, 0x89, 0x33, 0x91, 0x52, 0x44, 0xbb,
	0x40, 0x59, 0x80, 0x0a, 0xa3, 0x51, 0xa5, 0xae, 0xcc, 0xe0, 0xa1, 0xd6, 0x10, 0xdb, 0xbd, 0x98,
	0x26, 0xd3, 0x0d, 0xf2, 0x80, 0x07, 0x91, 0x98, 0x6b, 0x84, 0xed, 0x76, 0x58, 0xf4, 0x11, 0xfa,
	0x12, 0x5d, 0x76, 0xdd, 0x87, 0xe8, 0x23, 0x75, 0xd7, 0xea, 0x5e, 0x1b, 0x63, 0x7e, 0x2a, 0x4d,
	0x9b, 0x0d, 0xe2, 0x7c, 0xe7, 0x3b, 0xff, 0xc7, 0xe7, 0x02, 0x44, 0xeb, 0xa5, 0xd7, 0x5c, 0xae,
	0x82, 0x28, 0xc0, 0x67, 0xb3, 0x20, 0x98, 0xf9, 0xa9, 0x74, 0x17, 0xdf, 0x9f, 0xbf, 0x4a, 0x80,
	0xd6, 0x06, 0x68, 0xb9, 0x74, 0x9d, 0x68, 0xcf, 0xbf, 0xda, 0x57, 0x85, 0x41, 0xbc, 0x9a, 0x78,
	0xe3, 0x49, 0x40, 0x23, 0xef, 0x21, 0x4a, 0x58, 0xf5, 0x5f, 0x45, 0x90, 0x9c, 0xf5, 0xd2, 0xc3,
	0x18, 0x24, 0xea, 0x2e, 0x3c, 0x55, 0xa8, 0x09, 0x0d, 0x85, 0xf0, 0xff, 0xb8, 0x09, 0xf2, 0xfd,
	0xdc, 0xf3, 0xa7, 0xa1, 0x2a, 0xd6, 0x0a, 0x8d, 0x72, 0xfb, 0x45, 0x73, 0x2f, 0x7e, 0xf3, 0x9a,
	0xa9, 0x49, 0xca, 0xc2, 0x2f, 0x40, 0x0e, 0xa8, 0x17, 0xdc, 0x87, 0x6a, 0xa1, 0x56, 0x68, 0x28,
	0x24, 0x95, 0xf0, 0xd7, 0x70, 0x12, 0x2c, 0xa3, 0x79, 0x40, 0x43, 0x55, 0xe2, 0x8e, 0x5e, 0x1e,
	0x38, 0xb2, 0xb8, 0x9e, 0x6c, 0x78, 0x58, 0x87, 0xea, 0x6e, 0xbe, 0x6a, 0xb1, 0x26, 0x34, 0xca,
	0xed, 0x37, 0x07, 0x96, 0x43, 0x4e, 0xbb, 0x4a, 0x58, 0xa4, 0x12, 0xe6, 0x45, 0xdc, 0x02, 0x39,
	0x5c, 0xd3, 0xc8, 0x7d, 0x50, 0xe5, 0x9a, 0xd0, 0xa8, 0x1e, 0x09, 0x3c, 0xe4, 0x6a, 0x92, 0xd2,
	0xea, 0x7f, 0xc8, 0x50, 0xe4, 0x45, 0xe1, 0x16, 0x48, 0x9f, 0xe6, 0x74, 0xca, 0x1b, 0x52, 0x6d,
	0xbf, 0x3e, 0x5e, 0x7a, 0xf3, 0x66, 0x4e, 0xa7, 0x84, 0x13, 0x71, 0x0f, 0xca, 0x13, 0x77, 0x35,
	0x9d, 0x53, 0xd7, 0x9f, 0x47, 0x6b, 0x55, 0xe4, 0x76, 0xf5, 0x7f, 0xb1, 0xbb, 0xda, 0x32, 0x49,
	0xde, 0x8c, 0xf5, 0x90, 0xc6, 0x8b, 0x3b, 0x6f, 0xa5, 0x16, 0x6a, 0x42, 0xa3, 0x48, 0x52, 0x29,
	0x9b, 0x8f, 0x94, 0x9b, 0xcf, 0x2b, 0x28, 0xb1, 0xe5, 0x18, 0xc7, 0x2b, 0x9f, 0xd7, 0xa7, 0x90,
	0x13, 0x26, 0x8f, 0x56, 0x3e, 0xfe, 0x02, 0xca, 0xbc, 0xf9, 0xe3, 0x39, 0x9d, 0x7a, 0x0f, 0xea,
	0x09, 0xf7, 0x05, 0x1c, 0x32, 0x18, 0xc2, 0xe2, 0x2c, 0xdd, 0xc9, 0x27, 0x6f, 0xaa, 0x96, 0x6a,
	0x42, 0xa3, 0x44, 0x52, 0x29, 0x3f, 0x2b, 0xe5, 0x91, 0xb3, 0x7a, 0x0d, 0xca, 0xc7, 0x30, 0xa0,
	0x63, 0x9e, 0x1f, 0xf0, 0x3c, 0x4a, 0x0c, 0x30, 0x59, 0x8e, 0x5f, 0x42, 0x65, 0xea, 0xdd, 0xbb,
	0xb1, 0x1f, 0x8d, 0x7f, 0x72, 0xfd, 0xd8, 0x53, 0xcb, 0x9c, 0x70, 0x9a, 0x82, 0x3f, 0x30, 0xac,
	0xfe, 0xa7, 0x08, 0x12, 0xeb, 0x24, 0x46, 0x70, 0xea, 0xdc, 0xda, 0xfa, 0x78, 0x64, 0xde, 0x98,
	0xd6, 0x7b, 0x13, 0x3d, 0xc1, 0x67, 0x50, 0xe6, 0x48, 0xcf, 0x1a, 0x75, 0x07, 0x3a, 0x12, 0x70,
	0x15, 0x80, 0x03, 0xd7, 0x03, 0x4b, 0x73, 0x90, 0x98, 0xc9, 0x86, 0xe9, 0x5c, 0x5e, 0xa0, 0x42,
	0x66, 0x30, 0x4a, 0x00, 0x29, 0x4f, 0xe8, 0xb4, 0x51, 0x31, 0x8b, 0x71, 0x6d, 0x7c, 0xd0, 0x7b,
	0x97, 0x17, 0x48, 0xde, 0x45, 0x3a, 0x6d, 0x74, 0x82, 0x2b, 0xa0, 0x70, 0xa4, 0x6b, 0x59, 0x03,
	0x54, 0xca, 0x7c, 0x0e, 0x1d, 0x62, 0x98, 0x7d, 0xa4, 0x64, 0x3e, 0xfb, 0xc4, 0x1a, 0xd9, 0x08,
	0x32, 0x0f, 0xef, 0xf4, 0xe1, 0x50, 0xeb, 0xeb, 0xa8, 0x9c, 0x31, 0xba, 0xb7, 0x8e, 0x3e, 0x44,
	0xa7, 0x3b, 0x69, 0x75, 0xda, 0xa8, 0x92, 0x85, 0xd0, 0xcd, 0xd1, 0x3b, 0x54, 0xc5, 0x4f, 0xa1,
	0x92, 0x84, 0xd8, 0x24, 0x71, 0xb6, 0x07, 0x5d, 0x5e, 0x20, 0xb4, 0x4d, 0x24, 0xf1, 0xf2, 0x74,
	0x07, 0xb8, 0xbc, 0x40, 0xb8, 0x1e, 0x41, 0x39, 0xb7, 0x5b, 0xf8, 0x25, 0x3c, 0xbb, 0xd2, 0x48,
	0xcf, 0x30, 0xb5, 0x81, 0xe1, 0xdc, 0xe6, 0xfa, 0xaa, 0xc2, 0xf3, 0xbc, 0xc2, 0xb2, 0x1d, 0xc3,
	0x32, 0xb5, 0x01, 0x12, 0xf6, 0x35, 0x44, 0xff, 0x7e, 0x64, 0x10, 0xbd, 0x87, 0xc4, 0x43, 0x8d,
	0xad, 0x6b, 0x8e, 0xde, 0x43, 0x85, 0xfa, 0xdf, 0x02, 0x48, 0x3a, 0x8d, 0x17, 0x47, 0xcf, 0xc8,
	0x37, 0xa0, 0x78, 0x34, 0x5e, 0x24, 0xe3, 0x4f, 0x2e, 0xc9, 0xf9, 0xc1, 0x52, 0x31, 0x6b, 0xbe,
	0x0c, 0x64, 0x4b, 0xce, 0x2f, 0x63, 0xe1, 0x7f, 0x1f, 0x0e, 0xe9, 0xf3, 0x0e, 0x47, 0xf1, 0x71,
	0x87, 0xe3, 0x23, 0x28, 0x59, 0x09, 0x47, 0xbb, 0xb0, 0xfd, 0xb0, 0xc5, 0x9d, 0x0f, 0xfb, 0xbf,
	0xd7, 0x58, 0xff, 0x0e, 0xe4, 0x04, 0x3a, 0x1a, 0xe8, 0x2d, 0x14, 0x37, 0xad, 0x66, 0x85, 0x3f,
	0x3f, 0x70, 0xa7, 0xd1, 0x35, 0x49, 0x28, 0x6f, 0x9b, 0x20, 0x27, 0x75, 0xb0, 0x65, 0x1b, 0xde,
	0x9a, 0x8e, 0xf6, 0x61, 0x6c, 0x13, 0xcb, 0xb1, 0xda, 0xe8, 0xc9, 0x3e, 0xd4, 0x41, 0x42, 0xf7,
	0x17, 0x78, 0x36, 0x09, 0x16, 0xfb, 0x1e, 0xbb, 0x0a, 0x7b, 0x42, 0x6c, 0x26, 0xd9, 0xc2, 0x8f,
	0xad, 0x54, 0x3b, 0x0b, 0x7c, 0x97, 0xce, 0x9a, 0xc1, 0x6a, 0xd6, 0x9a, 0x79, 0x94, 0x73, 0xb7,
	0x8f, 0xd1, 0x92, 0x1d, 0xaa, 0x6f, 0xf9, 0xef, 0x5f, 0x82, 0xf0, 0x9b, 0x58, 0xe8, 0xdb, 0xdd,
	0xdf, 0xc5, 0x37, 0xfd, 0xc4, 0xd4, 0xde, 0xa4, 0xfa, 0xde, 0xf3, 0xfd, 0x1b, 0x1a, 0xfc, 0x4c,
	0x59, 0x80, 0xf0, 0x4e, 0xe6, 0xf6, 0x9d, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xd1, 0x68,
	0xe4, 0x14, 0x07, 0x00, 0x00,
}
