// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd-response.proto

package mock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  CmdResponse
//
type CmdResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *CmdResponse) Reset()         { *m = CmdResponse{} }
func (m *CmdResponse) String() string { return proto.CompactTextString(m) }
func (*CmdResponse) ProtoMessage()    {}
func (*CmdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b039e11bdfc3a7ef, []int{0}
}

func (m *CmdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdResponse.Unmarshal(m, b)
}
func (m *CmdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdResponse.Marshal(b, m, deterministic)
}
func (m *CmdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdResponse.Merge(m, src)
}
func (m *CmdResponse) XXX_Size() int {
	return xxx_messageInfo_CmdResponse.Size(m)
}
func (m *CmdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CmdResponse proto.InternalMessageInfo

func (m *CmdResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*CmdResponse)(nil), "CmdResponse")
}

func init() { proto.RegisterFile("cmd-response.proto", fileDescriptor_b039e11bdfc3a7ef) }

var fileDescriptor_b039e11bdfc3a7ef = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xce, 0x4d, 0xd1,
	0x2d, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52,
	0xe6, 0xe2, 0x76, 0xce, 0x4d, 0x09, 0x82, 0x0a, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94,
	0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x49, 0x6c, 0x60, 0xb5, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x9f, 0x99, 0xa1, 0x41, 0x00, 0x00, 0x00,
}


func (m *CmdResponse) XXX_MapID() uint16 {
	return 1005
}

func (m *CmdResponse) XXX_MapName() string {
	return "CmdResponse"
}
