// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd-deadline.proto

package mock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  CmdDeadline
//
type CmdDeadline struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *CmdDeadline) Reset()         { *m = CmdDeadline{} }
func (m *CmdDeadline) String() string { return proto.CompactTextString(m) }
func (*CmdDeadline) ProtoMessage()    {}
func (*CmdDeadline) Descriptor() ([]byte, []int) {
	return fileDescriptor_683accac823075ab, []int{0}
}

func (m *CmdDeadline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdDeadline.Unmarshal(m, b)
}
func (m *CmdDeadline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdDeadline.Marshal(b, m, deterministic)
}
func (m *CmdDeadline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdDeadline.Merge(m, src)
}
func (m *CmdDeadline) XXX_Size() int {
	return xxx_messageInfo_CmdDeadline.Size(m)
}
func (m *CmdDeadline) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdDeadline.DiscardUnknown(m)
}

var xxx_messageInfo_CmdDeadline proto.InternalMessageInfo

func (m *CmdDeadline) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*CmdDeadline)(nil), "CmdDeadline")
}

func init() { proto.RegisterFile("cmd-deadline.proto", fileDescriptor_683accac823075ab) }

var fileDescriptor_683accac823075ab = []byte{
	// 76 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xce, 0x4d, 0xd1,
	0x4d, 0x49, 0x4d, 0x4c, 0xc9, 0xc9, 0xcc, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52,
	0xe4, 0xe2, 0x76, 0xce, 0x4d, 0x71, 0x81, 0x0a, 0x0a, 0x09, 0x71, 0xb1, 0x94, 0xa4, 0x56, 0x94,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0x95, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x7e, 0x06, 0x27, 0x85, 0x3f, 0x00, 0x00, 0x00,
}


func (m *CmdDeadline) XXX_MapID() uint16 {
	return 1002
}

func (m *CmdDeadline) XXX_MapName() string {
	return "CmdDeadline"
}
