// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd-slow.proto

package mock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  CmdSlow
//
type CmdSlow struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *CmdSlow) Reset()         { *m = CmdSlow{} }
func (m *CmdSlow) String() string { return proto.CompactTextString(m) }
func (*CmdSlow) ProtoMessage()    {}
func (*CmdSlow) Descriptor() ([]byte, []int) {
	return fileDescriptor_0362dae7a3e603b3, []int{0}
}

func (m *CmdSlow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdSlow.Unmarshal(m, b)
}
func (m *CmdSlow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdSlow.Marshal(b, m, deterministic)
}
func (m *CmdSlow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdSlow.Merge(m, src)
}
func (m *CmdSlow) XXX_Size() int {
	return xxx_messageInfo_CmdSlow.Size(m)
}
func (m *CmdSlow) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdSlow.DiscardUnknown(m)
}

var xxx_messageInfo_CmdSlow proto.InternalMessageInfo

func (m *CmdSlow) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*CmdSlow)(nil), "CmdSlow")
}

func init() { proto.RegisterFile("cmd-slow.proto", fileDescriptor_0362dae7a3e603b3) }

var fileDescriptor_0362dae7a3e603b3 = []byte{
	// 73 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0x4d, 0xd1,
	0x2d, 0xce, 0xc9, 0x2f, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe5, 0x62, 0x77, 0xce,
	0x4d, 0x09, 0xce, 0xc9, 0x2f, 0x17, 0x12, 0xe2, 0x62, 0x29, 0x49, 0xad, 0x28, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0xaa, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x81, 0x2b, 0x9c, 0x8b, 0x37, 0x00, 0x00, 0x00,
}


func (m *CmdSlow) XXX_MapID() uint16 {
	return 1006
}

func (m *CmdSlow) XXX_MapName() string {
	return "CmdSlow"
}
