// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd-no-respond.proto

package mock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  CmdNoRespond
//
type CmdNoRespond struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *CmdNoRespond) Reset()         { *m = CmdNoRespond{} }
func (m *CmdNoRespond) String() string { return proto.CompactTextString(m) }
func (*CmdNoRespond) ProtoMessage()    {}
func (*CmdNoRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_aff82e885ca5e924, []int{0}
}

func (m *CmdNoRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdNoRespond.Unmarshal(m, b)
}
func (m *CmdNoRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdNoRespond.Marshal(b, m, deterministic)
}
func (m *CmdNoRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdNoRespond.Merge(m, src)
}
func (m *CmdNoRespond) XXX_Size() int {
	return xxx_messageInfo_CmdNoRespond.Size(m)
}
func (m *CmdNoRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdNoRespond.DiscardUnknown(m)
}

var xxx_messageInfo_CmdNoRespond proto.InternalMessageInfo

func (m *CmdNoRespond) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*CmdNoRespond)(nil), "CmdNoRespond")
}

func init() { proto.RegisterFile("cmd-no-respond.proto", fileDescriptor_aff82e885ca5e924) }

var fileDescriptor_aff82e885ca5e924 = []byte{
	// 80 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0x4d, 0xd1,
	0xcd, 0xcb, 0xd7, 0x2d, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x57, 0x52, 0xe2, 0xe2, 0x71, 0xce, 0x4d, 0xf1, 0xcb, 0x0f, 0x82, 0x88, 0x0a, 0x09, 0x71, 0xb1,
	0x94, 0xa4, 0x56, 0x94, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x49, 0x6c, 0x60,
	0xa5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x11, 0xa9, 0xe0, 0x5c, 0x42, 0x00, 0x00, 0x00,
}


func (m *CmdNoRespond) XXX_MapID() uint16 {
	return 1003
}

func (m *CmdNoRespond) XXX_MapName() string {
	return "CmdNoRespond"
}
