// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deadline_action.proto

package mock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  DeadlineAction
//
type DeadlineAction struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *DeadlineAction) Reset()         { *m = DeadlineAction{} }
func (m *DeadlineAction) String() string { return proto.CompactTextString(m) }
func (*DeadlineAction) ProtoMessage()    {}
func (*DeadlineAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_07fb1fbf53e2658a, []int{0}
}

func (m *DeadlineAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeadlineAction.Unmarshal(m, b)
}
func (m *DeadlineAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeadlineAction.Marshal(b, m, deterministic)
}
func (m *DeadlineAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeadlineAction.Merge(m, src)
}
func (m *DeadlineAction) XXX_Size() int {
	return xxx_messageInfo_DeadlineAction.Size(m)
}
func (m *DeadlineAction) XXX_DiscardUnknown() {
	xxx_messageInfo_DeadlineAction.DiscardUnknown(m)
}

var xxx_messageInfo_DeadlineAction proto.InternalMessageInfo

func (m *DeadlineAction) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*DeadlineAction)(nil), "DeadlineAction")
}

func init() { proto.RegisterFile("deadline_action.proto", fileDescriptor_07fb1fbf53e2658a) }

var fileDescriptor_07fb1fbf53e2658a = []byte{
	// 79 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x49, 0x4d, 0x4c,
	0xc9, 0xc9, 0xcc, 0x4b, 0x8d, 0x4f, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x57, 0x52, 0xe1, 0xe2, 0x73, 0x81, 0x4a, 0x38, 0x82, 0xc5, 0x85, 0x84, 0xb8, 0x58, 0x4a,
	0x52, 0x2b, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0xec, 0x24, 0x36, 0xb0, 0x62,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0x25, 0x38, 0xa0, 0x45, 0x00, 0x00, 0x00,
}


func (m *DeadlineAction) XXX_MapID() uint16 {
	return 1001
}

func (m *DeadlineAction) XXX_MapName() string {
	return "DeadlineAction"
}
