// Code generated by proto watcher. DO NOT EDIT.
package mock

//MapXXX mapping ID to object
type MapXXX struct {
}

// NewObjectByID return new object from id
func (r *MapXXX) NewObjectByID(id uint16) (interface{}) {
	switch id {
	case 1001: return new(DeadlineAction)
	case 1002: return new(NoRespondAction)
	case 1003: return new(RespondAction)
	case 1004: return new(SlowAction)
	case 1005: return new(BigDataAction)
	}
	return nil
}
