// Code generated by protoc-gen-go. DO NOT EDIT.
// source: no_respond_action.proto

package mock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  NoRespondAction
//
type NoRespondAction struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *NoRespondAction) Reset()         { *m = NoRespondAction{} }
func (m *NoRespondAction) String() string { return proto.CompactTextString(m) }
func (*NoRespondAction) ProtoMessage()    {}
func (*NoRespondAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0343de2cb9d281, []int{0}
}

func (m *NoRespondAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoRespondAction.Unmarshal(m, b)
}
func (m *NoRespondAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoRespondAction.Marshal(b, m, deterministic)
}
func (m *NoRespondAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoRespondAction.Merge(m, src)
}
func (m *NoRespondAction) XXX_Size() int {
	return xxx_messageInfo_NoRespondAction.Size(m)
}
func (m *NoRespondAction) XXX_DiscardUnknown() {
	xxx_messageInfo_NoRespondAction.DiscardUnknown(m)
}

var xxx_messageInfo_NoRespondAction proto.InternalMessageInfo

func (m *NoRespondAction) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*NoRespondAction)(nil), "NoRespondAction")
}

func init() { proto.RegisterFile("no_respond_action.proto", fileDescriptor_ad0343de2cb9d281) }

var fileDescriptor_ad0343de2cb9d281 = []byte{
	// 83 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcf, 0xcb, 0x8f, 0x2f,
	0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x4b, 0x89, 0x4f, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe5, 0xe2, 0xf7, 0xcb, 0x0f, 0x82, 0xc8, 0x38, 0x82, 0x25, 0x84,
	0x84, 0xb8, 0x58, 0x4a, 0x52, 0x2b, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0xec,
	0x24, 0x36, 0xb0, 0x6a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0x5c, 0x9c, 0x35, 0x48,
	0x00, 0x00, 0x00,
}


func (m *NoRespondAction) XXX_MapID() uint16 {
	return 1002
}

func (m *NoRespondAction) XXX_MapName() string {
	return "NoRespondAction"
}
