// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb-ok.proto

package shared

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  OK response
//
type PbOK struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *PbOK) Reset()         { *m = PbOK{} }
func (m *PbOK) String() string { return proto.CompactTextString(m) }
func (*PbOK) ProtoMessage()    {}
func (*PbOK) Descriptor() ([]byte, []int) {
	return fileDescriptor_b18acbc73ed0e933, []int{0}
}

func (m *PbOK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbOK.Unmarshal(m, b)
}
func (m *PbOK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbOK.Marshal(b, m, deterministic)
}
func (m *PbOK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbOK.Merge(m, src)
}
func (m *PbOK) XXX_Size() int {
	return xxx_messageInfo_PbOK.Size(m)
}
func (m *PbOK) XXX_DiscardUnknown() {
	xxx_messageInfo_PbOK.DiscardUnknown(m)
}

var xxx_messageInfo_PbOK proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PbOK)(nil), "PbOK")
}

func init() { proto.RegisterFile("pb-ok.proto", fileDescriptor_b18acbc73ed0e933) }

var fileDescriptor_b18acbc73ed0e933 = []byte{
	// 50 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x48, 0xd2, 0xcd,
	0xcf, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x62, 0xe3, 0x62, 0x09, 0x48, 0xf2, 0xf7, 0x4e,
	0x62, 0x03, 0x73, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xf1, 0xd2, 0x78, 0x1d, 0x00,
	0x00, 0x00,
}


func (m *PbOK) XXX_MapID() uint16 {
	return 4
}

func (m *PbOK) XXX_MapName() string {
	return "PbOK"
}
