// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb-string.proto

package shared

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  string response
//
type PbString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *PbString) Reset()         { *m = PbString{} }
func (m *PbString) String() string { return proto.CompactTextString(m) }
func (*PbString) ProtoMessage()    {}
func (*PbString) Descriptor() ([]byte, []int) {
	return fileDescriptor_456717cdfe036dcb, []int{0}
}

func (m *PbString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbString.Unmarshal(m, b)
}
func (m *PbString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbString.Marshal(b, m, deterministic)
}
func (m *PbString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbString.Merge(m, src)
}
func (m *PbString) XXX_Size() int {
	return xxx_messageInfo_PbString.Size(m)
}
func (m *PbString) XXX_DiscardUnknown() {
	xxx_messageInfo_PbString.DiscardUnknown(m)
}

var xxx_messageInfo_PbString proto.InternalMessageInfo

func (m *PbString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*PbString)(nil), "PbString")
}

func init() { proto.RegisterFile("pb-string.proto", fileDescriptor_456717cdfe036dcb) }

var fileDescriptor_456717cdfe036dcb = []byte{
	// 73 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x48, 0xd2, 0x2d,
	0x2e, 0x29, 0xca, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe0, 0xe2, 0x08,
	0x48, 0x0a, 0x06, 0x8b, 0x08, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x49, 0x6c, 0x60, 0x85, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xed, 0x50, 0x44, 0x3b, 0x3b, 0x00, 0x00, 0x00,
}


func (m *PbString) XXX_MapID() uint16 {
	return 5
}

func (m *PbString) XXX_MapName() string {
	return "PbString"
}
