// Code generated by proto watcher. DO NOT EDIT.
package pb

//MapXXX mapping ID to object
type MapXXX struct {
}

// NewObjectByID return new object from id
func (r *MapXXX) NewObjectByID(id uint16) (interface{}) {
	switch id {
	case 1: return new(Bool)
	case 2: return new(Error)
	case 3: return new(Number)
	case 4: return new(OK)
	case 5: return new(String)
	}
	return nil
}
