// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ok.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  OK response
//
type OK struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *OK) Reset()         { *m = OK{} }
func (m *OK) String() string { return proto.CompactTextString(m) }
func (*OK) ProtoMessage()    {}
func (*OK) Descriptor() ([]byte, []int) {
	return fileDescriptor_9026e66a375a14b8, []int{0}
}

func (m *OK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OK.Unmarshal(m, b)
}
func (m *OK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OK.Marshal(b, m, deterministic)
}
func (m *OK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OK.Merge(m, src)
}
func (m *OK) XXX_Size() int {
	return xxx_messageInfo_OK.Size(m)
}
func (m *OK) XXX_DiscardUnknown() {
	xxx_messageInfo_OK.DiscardUnknown(m)
}

var xxx_messageInfo_OK proto.InternalMessageInfo

func init() {
	proto.RegisterType((*OK)(nil), "OK")
}

func init() { proto.RegisterFile("ok.proto", fileDescriptor_9026e66a375a14b8) }

var fileDescriptor_9026e66a375a14b8 = []byte{
	// 45 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0xcf, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x57, 0x62, 0xe1, 0x62, 0xf2, 0xf7, 0x4e, 0x62, 0x03, 0x73, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x64, 0x30, 0x88, 0x6d, 0x18, 0x00, 0x00, 0x00,
}


func (m *OK) XXX_MapID() uint16 {
	return 4
}

func (m *OK) XXX_MapName() string {
	return "OK"
}
