// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb-bool.proto

package shared

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  bool response
//
type PbBool struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *PbBool) Reset()         { *m = PbBool{} }
func (m *PbBool) String() string { return proto.CompactTextString(m) }
func (*PbBool) ProtoMessage()    {}
func (*PbBool) Descriptor() ([]byte, []int) {
	return fileDescriptor_b304491e16ee92f2, []int{0}
}

func (m *PbBool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbBool.Unmarshal(m, b)
}
func (m *PbBool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbBool.Marshal(b, m, deterministic)
}
func (m *PbBool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbBool.Merge(m, src)
}
func (m *PbBool) XXX_Size() int {
	return xxx_messageInfo_PbBool.Size(m)
}
func (m *PbBool) XXX_DiscardUnknown() {
	xxx_messageInfo_PbBool.DiscardUnknown(m)
}

var xxx_messageInfo_PbBool proto.InternalMessageInfo

func (m *PbBool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func init() {
	proto.RegisterType((*PbBool)(nil), "PbBool")
}

func init() { proto.RegisterFile("pb-bool.proto", fileDescriptor_b304491e16ee92f2) }

var fileDescriptor_b304491e16ee92f2 = []byte{
	// 72 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0xd2, 0x4d,
	0xca, 0xcf, 0xcf, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe3, 0x62, 0x0b, 0x48, 0x72,
	0xca, 0xcf, 0xcf, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x08, 0x82, 0x70, 0x92, 0xd8, 0xc0, 0xca, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x98, 0xda, 0x43, 0xb7, 0x37, 0x00, 0x00, 0x00,
}


func (m *PbBool) XXX_MapID() uint16 {
	return 3
}

func (m *PbBool) XXX_MapName() string {
	return "PbBool"
}
