// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb-int.proto

package shared

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  int32 response
//
type PbInt struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" firestore:"-"`
	XXX_unrecognized     []byte   `json:"-" firestore:"-"`
	XXX_sizecache        int32    `json:"-" firestore:"-"`
}

func (m *PbInt) Reset()         { *m = PbInt{} }
func (m *PbInt) String() string { return proto.CompactTextString(m) }
func (*PbInt) ProtoMessage()    {}
func (*PbInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e3fe28d7145f360, []int{0}
}

func (m *PbInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbInt.Unmarshal(m, b)
}
func (m *PbInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbInt.Marshal(b, m, deterministic)
}
func (m *PbInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbInt.Merge(m, src)
}
func (m *PbInt) XXX_Size() int {
	return xxx_messageInfo_PbInt.Size(m)
}
func (m *PbInt) XXX_DiscardUnknown() {
	xxx_messageInfo_PbInt.DiscardUnknown(m)
}

var xxx_messageInfo_PbInt proto.InternalMessageInfo

func (m *PbInt) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*PbInt)(nil), "PbInt")
}

func init() { proto.RegisterFile("pb-int.proto", fileDescriptor_4e3fe28d7145f360) }

var fileDescriptor_4e3fe28d7145f360 = []byte{
	// 70 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0xd2, 0xcd,
	0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe5, 0x62, 0x0d, 0x48, 0xf2, 0xcc,
	0x2b, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x0d, 0x82, 0x70, 0x92, 0xd8, 0xc0, 0xaa, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x38, 0xc0,
	0xc6, 0x92, 0x35, 0x00, 0x00, 0x00,
}


func (m *PbInt) XXX_MapID() uint16 {
	return 2
}

func (m *PbInt) XXX_MapName() string {
	return "PbInt"
}
